events {
}

http {
    log_format main
        '$remote_addr '
        '[$time_local] '
        '"$request" '
        '$status '
        '$body_bytes_sent '
        '$request_time '
        '$upstream_response_time '
        '$upstream_addr '
        '"$http_user_agent"';

    access_log /dev/stdout main;
    error_log /dev/stderr warn;

    server {
        listen 80;

        location / {
            proxy_pass http://frontend:3000;
        }

        location /api {
            proxy_pass http://backend:8080;
        }
    }
}