location / {
    limit_req zone=frontend burst=50 nodelay;

    proxy_pass http://frontend:3000;
}

location /api/login {
    limit_req zone=auth burst=5 nodelay;

    proxy_pass http://backend:8080;
}

location /oauth2 {
    limit_req zone=auth burst=5 nodelay;

    proxy_pass http://backend:8080;
}

location /login/oauth2 {
    limit_req zone=auth burst=5 nodelay;

    proxy_pass http://backend:8080;
}

location /api {
    limit_req zone=api burst=20 nodelay;

    proxy_pass http://backend:8080;

    # Buffering when OCR async, heavy responses:
    # proxy_buffering on;
    # proxy_buffers 16 16k;
    # proxy_buffer_size 16k;

}