server {

    listen 80;

    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl;
    http2 on;
    
    server_name spendtracker.arielestebansoto.com;

    ssl_certificate /etc/letsencrypt/live/spendtracker.arielestebansoto.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/spendtracker.arielsoto.com/privkey.pem;

    include /etc/nginx/common/locations.conf;
}