server {
    listen 80;
    
    listen 443 ssl;
    
    ssl_certificate     /etc/nginx/certs/localhost.pem;
    ssl_certificate_key /etc/nginx/certs/localhost-key.pem;

    include /etc/nginx/common/locations.conf;
}