server {
    listen 80;
    
    listen 443 ssl;
    
    ssl_certificate     /etc/nginx/project/dev/certs/localhost.pem;
    ssl_certificate_key /etc/nginx/project/dev/certs/localhost-key.pem;

    include /etc/nginx/project/common/locations.conf;
}