spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        jdbc:
          time_zone: UTC
  
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret: 
          google:
            client-id: 
            client-secret: 
            scope:
              - openid
              - profile
              - email

app:
  csrf:
    ignore-urls: 
  oauth2:
    default-success-url: 
  logout:
    logout-url: 
  cors:
    allowed-origins: 
    allowed-methods: 
  storage:
    local:
      path: uploads