server:
  forward-headers-strategy: framework

  tomcat:
    threads:
      max: 50
      min-spare: 5

  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: lax
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN