spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        jdbc:
          time_zone: UTC
  
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration

app:
  storage:
    local:
      path: uploads